-- ================================================
-- SQL Script: Error Logging
-- Project   : Library Management System
-- Author    : Akshay - July 2025
-- Encoding  : UTF-8
-- ================================================

-- ================================================
-- 1. Error Logs Table
-- Purpose: Stores error messages with procedure name and timestamp
-- ================================================
CREATE TABLE error_logs (
    log_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_date      DATE DEFAULT SYSDATE,
    procedure_name  VARCHAR2(100),
    error_message   VARCHAR2(4000)
);

-- ================================================
-- 2. Procedure: log_error
-- Purpose: Inserts error details into error_logs table
-- ================================================
CREATE OR REPLACE PROCEDURE log_error(
    p_procedure_name IN VARCHAR2,
    p_error_message  IN VARCHAR2
)
AS
BEGIN
    INSERT INTO error_logs (procedure_name, error_message)
    VALUES (p_procedure_name, p_error_message);

    COMMIT;
END;
/


-- ================================================
-- End of Script
-- ================================================
